
[[tool.uv.index]]
url = "https://mirrors.hust.edu.cn/pypi/web/simple/"
default = true

[tool.uv.workspace]
members = [
    "pyhuskarui",
    "utils",
    "gallery",
]

[tool.uv.sources]
pyhuskarui = { workspace = true }
gallery = { workspace = true }
utils = { workspace = true }

[dependency-groups]
dev = [  
    "utils",
]