[[tool.uv.index]]
default = true
url = "https://mirrors.hust.edu.cn/pypi/web/simple/"

[tool.uv.workspace]
members = [
  "pyhuskarui",
  "utils",
  "gallery",
]

[tool.uv.sources]
gallery = {workspace = true}
pyhuskarui = {workspace = true}
utils = {workspace = true}

[dependency-groups]
dev = [
  "utils",
]
